name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-workflow:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
      - uses: csiimnida/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: master
          IMAGES_FOLDER: images
          COMMIT_MESSAGE: "📊"
